enum ActionTypes {
  ADD_FILTER_HISTORY   = 'ADD_FILTER_HISTORY',
  CLEAR_FILTER_HISTORY = 'CLEAR_FILTER_HISTORY',
  RESET_FILTER_HISTORY = 'RESET_FILTER_HISTORY',
  UNDO_FILTER_HISTORY  = 'UNDO_FILTER_HISTORY',
  REDO_FILTER_HISTORY  = 'REDO_FILTER_HISTORY',
  SET_DIRTY_FILTER_HISTORY = 'SET_DIRTY_FILTER_HISTORY'
}

export default ActionTypes