enum ActionTypes {
  UPSERT_FILTER_SET_THUMBNAIL = 'UPSERT_FILTER_SET_THUMBNAIL',
  DELETE_FILTER_SET_THUMBNAIL = 'DELETE_FILTER_SET_THUMBNAIL',
  CLEAR_FILTER_SET_THUMBNAIL  = 'CLEAR_FILTER_SET_THUMBNAIL',
  RESET_FILTER_SET_THUMBNAIL  = 'RESET_FILTER_SET_THUMBNAIL'
}

export default ActionTypes