enum ActionTypes {
  UPSERT_FILTER_VALUE = 'UPSERT_FILTER_VALUE',
  DELETE_FILTER_VALUE = 'DELETE_FILTER_VALUE',
  CLEAR_FILTER_VALUE  = 'CLEAR_FILTER_VALUE',
  RESET_FILTER_VALUE  = 'RESET_FILTER_VALUE'
}

export default ActionTypes